/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetointersistemaestoque;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class MenuCadastroItens extends javax.swing.JFrame {
    //objetos responsáveis por chamarem os métodos que adicionarão os produtos cadastrados em seu devido arraylist
    CamisaPolo cp = new CamisaPolo();
    Camiseta c = new Camiseta();
    BlusaMoletom bm = new BlusaMoletom();
    
    public MenuCadastroItens() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        campoCorCad = new javax.swing.JTextField();
        txtItem = new javax.swing.JLabel();
        txtCor = new javax.swing.JLabel();
        campoIdCad = new javax.swing.JTextField();
        txtPrecoCusto = new javax.swing.JLabel();
        campoPrecoCustoCad = new javax.swing.JTextField();
        txtPrecoVenda = new javax.swing.JLabel();
        campoPrecoVendaCad = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        cmbItemCad = new javax.swing.JComboBox<>();
        txtQuantidade = new javax.swing.JLabel();
        campoQuantidadeCad = new javax.swing.JTextField();
        txtITamanho = new javax.swing.JLabel();
        cmbTamanhoCad = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel1.setText("Cadastro");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtId.setText("ID:");

        campoCorCad.setBackground(new java.awt.Color(255, 204, 102));
        campoCorCad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoCorCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCorCadActionPerformed(evt);
            }
        });

        txtItem.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtItem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtItem.setText("Item:");

        txtCor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtCor.setText("Cor:");

        campoIdCad.setBackground(new java.awt.Color(255, 204, 102));
        campoIdCad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoIdCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdCadActionPerformed(evt);
            }
        });

        txtPrecoCusto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPrecoCusto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtPrecoCusto.setText("Preco Custo:");

        campoPrecoCustoCad.setBackground(new java.awt.Color(255, 204, 102));
        campoPrecoCustoCad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoPrecoCustoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrecoCustoCadActionPerformed(evt);
            }
        });

        txtPrecoVenda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPrecoVenda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtPrecoVenda.setText("Preco Venda:");

        campoPrecoVendaCad.setBackground(new java.awt.Color(255, 204, 102));
        campoPrecoVendaCad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoPrecoVendaCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrecoVendaCadActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(255, 160, 19));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        cmbItemCad.setBackground(new java.awt.Color(255, 204, 102));
        cmbItemCad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbItemCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Blusa Moletom", "Camisa Polo", "Camiseta" }));
        cmbItemCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItemCadActionPerformed(evt);
            }
        });

        txtQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtQuantidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtQuantidade.setText("Quantidade:");

        campoQuantidadeCad.setBackground(new java.awt.Color(255, 204, 102));
        campoQuantidadeCad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoQuantidadeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoQuantidadeCadActionPerformed(evt);
            }
        });

        txtITamanho.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtITamanho.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtITamanho.setText("Tamanho:");

        cmbTamanhoCad.setBackground(new java.awt.Color(255, 204, 102));
        cmbTamanhoCad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbTamanhoCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "P", "M", "G", "GG" }));
        cmbTamanhoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTamanhoCadActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 160, 19));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(257, 257, 257)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtITamanho)
                            .addGap(18, 18, 18)
                            .addComponent(cmbTamanhoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPrecoVenda)
                                .addComponent(txtPrecoCusto)
                                .addComponent(txtQuantidade))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoQuantidadeCad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoPrecoCustoCad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoPrecoVendaCad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbItemCad, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoCorCad, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(campoIdCad, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnCadastrar)
                        .addGap(92, 92, 92)
                        .addComponent(btnVoltar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbItemCad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtITamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTamanhoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCorCad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIdCad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPrecoCustoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPrecoVendaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoQuantidadeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoCorCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCorCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCorCadActionPerformed

    private void campoIdCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdCadActionPerformed

    private void campoPrecoCustoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPrecoCustoCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPrecoCustoCadActionPerformed

    private void campoPrecoVendaCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPrecoVendaCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPrecoVendaCadActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        //objetos que receberão os atributos setados pelo usuário ao efetuar o cadastro do produto
        //para posteriormente serem adicionados no sistema                                              
        CamisaPolo camisaPolo = new CamisaPolo();
        Camiseta camiseta = new Camiseta();
        BlusaMoletom blusaMoletom = new BlusaMoletom();
        
        //o sistema verifica o tipo de item selecionado, para adicionar os atributos digitados pelo usuario ao objeto criado                                                                                
        if (cmbItemCad.getSelectedItem() == "Camisa Polo"){ 
            camisaPolo.setItem(cmbItemCad.getSelectedItem().toString());
            camisaPolo.setTamanho(cmbTamanhoCad.getSelectedItem().toString());
            camisaPolo.setCor(campoCorCad.getText().toUpperCase());
            camisaPolo.setId(campoIdCad.getText());
            camisaPolo.setPrecoCusto(Double.parseDouble(campoPrecoCustoCad.getText()));
            camisaPolo.setPrecoVenda(Double.parseDouble(campoPrecoCustoCad.getText()));
            camisaPolo.setQuantidade(Integer.parseInt(campoPrecoCustoCad.getText()));
            
            //o método add retorna true se o obj for adicionado no arraylist                                                                                                        
            if(cp.add(camisaPolo)){    
                JOptionPane.showMessageDialog(null, "Cadastro Efetuado");
                campoCorCad.setText("");
                campoPrecoCustoCad.setText("");
                campoPrecoVendaCad.setText("");
                campoQuantidadeCad.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar Camisa Polo");
            }
            
        }else if (cmbItemCad.getSelectedItem() == "Camiseta"){
           
           camiseta.setItem(cmbItemCad.getSelectedItem().toString());
           camiseta.setTamanho(cmbTamanhoCad.getSelectedItem().toString());
           camiseta.setCor(campoCorCad.getText().toUpperCase());
           camiseta.setId(campoIdCad.getText());
           camiseta.setPrecoCusto(Double.parseDouble(campoPrecoCustoCad.getText()));
           camiseta.setPrecoVenda(Double.parseDouble(campoPrecoVendaCad.getText()));
           camiseta.setQuantidade(Integer.parseInt(campoQuantidadeCad.getText()));
           
           
            if(c.add(camiseta)){
                JOptionPane.showMessageDialog(null, "Cadastro Efetuado");
                
                campoCorCad.setText("");
                campoPrecoCustoCad.setText("");
                campoPrecoVendaCad.setText("");
                campoQuantidadeCad.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar Camiseta");
            }
            
        }else if (cmbItemCad.getSelectedItem() == "Blusa Moletom"){
           
           blusaMoletom.setItem(cmbItemCad.getSelectedItem().toString());
           blusaMoletom.setTamanho(cmbTamanhoCad.getSelectedItem().toString());
           blusaMoletom.setCor(campoCorCad.getText().toUpperCase());
           blusaMoletom.setId(campoIdCad.getText());
           blusaMoletom.setPrecoCusto(Double.parseDouble(campoPrecoCustoCad.getText()));
           blusaMoletom.setPrecoVenda(Double.parseDouble(campoPrecoVendaCad.getText()));
           blusaMoletom.setQuantidade(Integer.parseInt(campoQuantidadeCad.getText()));
           
           
            if (bm.add(blusaMoletom)){
                JOptionPane.showMessageDialog(null, "Cadastro Efetuado");
                
                campoCorCad.setText("");
                campoPrecoCustoCad.setText("");
                campoPrecoVendaCad.setText("");
                campoQuantidadeCad.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar Blusa Moletom");
            }
            
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void campoQuantidadeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoQuantidadeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoQuantidadeCadActionPerformed

    private void cmbTamanhoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTamanhoCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTamanhoCadActionPerformed

    private void cmbItemCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItemCadActionPerformed
        // TODO add your handling code here:
        if (cmbItemCad.getSelectedItem() == "Blusa Moletom"){
            campoIdCad.setText("100");
        }else if (cmbItemCad.getSelectedItem() == "Camisa Polo"){
            campoIdCad.setText("150");
        }else if (cmbItemCad.getSelectedItem() == "Camiseta"){
            campoIdCad.setText("200");
        }else{
            campoIdCad.setText("");
        }
    }//GEN-LAST:event_cmbItemCadActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCadastroItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCadastroItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCadastroItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCadastroItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCadastroItens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField campoCorCad;
    private javax.swing.JTextField campoIdCad;
    private javax.swing.JTextField campoPrecoCustoCad;
    private javax.swing.JTextField campoPrecoVendaCad;
    private javax.swing.JTextField campoQuantidadeCad;
    private javax.swing.JComboBox<String> cmbItemCad;
    private javax.swing.JComboBox<String> cmbTamanhoCad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtCor;
    private javax.swing.JLabel txtITamanho;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtItem;
    private javax.swing.JLabel txtPrecoCusto;
    private javax.swing.JLabel txtPrecoVenda;
    private javax.swing.JLabel txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
