/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetointersistemaestoque;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class MenuRelatorio extends javax.swing.JFrame {
    //objetos responsáveis por chamarem os métodos que adicionarão os produtos cadastrados em seu devido arraylist
    BlusaMoletom bm = new BlusaMoletom();
    CamisaPolo cp = new CamisaPolo();
    Camiseta c = new Camiseta();
    
    public MenuRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        txtProduto = new javax.swing.JLabel();
        cmbProdutoRel = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório");

        tabelaProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item", "Tamanho", "Cor", "Preço Custo", "Preço Venda", "Quantidade"
            }
        ));
        tabelaProduto.setRowHeight(40);
        jScrollPane1.setViewportView(tabelaProduto);

        txtProduto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProduto.setText("Produto");
        txtProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cmbProdutoRel.setBackground(new java.awt.Color(255, 204, 102));
        cmbProdutoRel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbProdutoRel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Blusa Moletom", "Camisa Polo", "Camiseta", "Todos" }));
        cmbProdutoRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProdutoRelActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 160, 19));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProdutoRel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(510, 510, 510)
                        .addComponent(btnVoltar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbProdutoRel)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cmbProdutoRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProdutoRelActionPerformed
        // TODO add your handling code here:
        if (cmbProdutoRel.getSelectedItem() == "Blusa Moletom"){
            //definindo modelo da tabela
            DefaultTableModel tblProduto = (DefaultTableModel) tabelaProduto.getModel();
            
            //limpar tabela
            for (int j = 0; j < tblProduto.getRowCount(); j++){
                tblProduto.removeRow(j);
                if(tblProduto.getRowCount() != 0){
                    while(tblProduto.getRowCount() != 0){
                        tblProduto.removeRow(0);
                    }
                }
            }
            
            //percorre o arraylist para adcionar todos os dados do arraylist na tabela
            for (int i = 0 ; i < bm.retornarBlusasMoletom().size(); i++){
                tblProduto.addRow(bm.dadosAtualizaTabelaBL(i));
            }
            
        }else if (cmbProdutoRel.getSelectedItem() == "Camisa Polo"){
            DefaultTableModel tblProduto = (DefaultTableModel) tabelaProduto.getModel();

            //limpar tabela
            for (int j = 0; j < tblProduto.getRowCount(); j++){
                tblProduto.removeRow(j);
                if(tblProduto.getRowCount() != 0){
                    while(tblProduto.getRowCount() != 0){
                        tblProduto.removeRow(0);
                    }
                }
            }

            for(int i = 0 ; i < cp.retornarCamisasPolo().size(); i++){
                tblProduto.addRow(cp.dadosAtualizaTabelaCP(i));
            }
                
        }else if (cmbProdutoRel.getSelectedItem() == "Camiseta"){
            DefaultTableModel tblProduto = (DefaultTableModel) tabelaProduto.getModel();
            
            //limpar tabela
            for (int j = 0; j < tblProduto.getRowCount(); j++){
                tblProduto.removeRow(j);
                if(tblProduto.getRowCount() != 0){
                    while(tblProduto.getRowCount() != 0){
                        tblProduto.removeRow(0);
                    }
                }
            }
            
            for (int i = 0; i < c.retornarCamisetas().size(); i++){
                tblProduto.addRow(c.dadosAtualizaTabelaC(i));
            }
        } else if (cmbProdutoRel.getSelectedItem() == "Todos"){
            DefaultTableModel tblProduto = (DefaultTableModel) tabelaProduto.getModel();
            
            //limpar tabela
            for (int j = 0; j < tblProduto.getRowCount(); j++){
                tblProduto.removeRow(j);
                if(tblProduto.getRowCount() != 0){
                    while(tblProduto.getRowCount() != 0){
                        tblProduto.removeRow(0);
                    }
                }
            }
            
            //percorre o vetor para definir nas novas variaveis os valores dos atributos no indice i, enquanto o i for menor que o tamanho do arraylist
            for (int i = 0 ; i < bm.retornarBlusasMoletom().size(); i++){
                tblProduto.addRow(bm.dadosAtualizaTabelaBL(i));
            }
            
            for(int i = 0 ; i < cp.retornarCamisasPolo().size(); i++){
                tblProduto.addRow(cp.dadosAtualizaTabelaCP(i));
            }
            
            for (int i = 0; i < c.retornarCamisetas().size(); i++){
                tblProduto.addRow(c.dadosAtualizaTabelaC(i));
            } 
        }
    }//GEN-LAST:event_cmbProdutoRelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbProdutoRel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JLabel txtProduto;
    // End of variables declaration//GEN-END:variables
}
